"""Migration description

Revision ID: 0ace577016a7
Revises: b9d63760620e
Create Date: 2025-03-27 11:40:23.169727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ace577016a7'
down_revision: Union[str, None] = 'b9d63760620e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testsprefattigroup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('generated', sa.Boolean(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('data_ora_inserimento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testsprefattigroup_id'), 'testsprefattigroup', ['id'], unique=False)
    op.add_column('testsgroup', sa.Column('testprefattigroup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'testsgroup', 'testsprefattigroup', ['testprefattigroup_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testsgroup', type_='foreignkey')
    op.drop_column('testsgroup', 'testprefattigroup_id')
    op.drop_index(op.f('ix_testsprefattigroup_id'), table_name='testsprefattigroup')
    op.drop_table('testsprefattigroup')
    # ### end Alembic commands ###
