"""Migration description

Revision ID: 11a7a36ef4c9
Revises: 716ebf732148
Create Date: 2025-03-19 16:47:53.578081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11a7a36ef4c9'
down_revision: Union[str, None] = '716ebf732148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('varianti', sa.Column('posizione', sa.Integer(), nullable=False))
    op.alter_column('varianti', 'corpo',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('varianti', 'corpo',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('varianti', 'posizione')
    # ### end Alembic commands ###
