"""Migration description

Revision ID: 1af55761fccc
Revises: 
Create Date: 2025-03-26 15:19:33.864439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af55761fccc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_admin',
    sa.Column('id_test_admin', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_test', sa.Integer(), nullable=False),
    sa.Column('data_ora_inserimento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=True),
    sa.Column('id_domanda', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_domanda'], ['domande.id_domanda'], ),
    sa.ForeignKeyConstraint(['id_test'], ['tests.id_test'], ),
    sa.PrimaryKeyConstraint('id_test_admin')
    )
    op.create_index(op.f('ix_test_admin_id_test_admin'), 'test_admin', ['id_test_admin'], unique=False)
    op.add_column('tests', sa.Column('contatore', sa.Integer(), nullable=True))
    op.drop_column('tests', 'nr_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('nr_test', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tests', 'contatore')
    op.drop_index(op.f('ix_test_admin_id_test_admin'), table_name='test_admin')
    op.drop_table('test_admin')
    # ### end Alembic commands ###
