"""Migration description

Revision ID: 29cd47decc2d
Revises: d1134cece895
Create Date: 2025-04-01 23:38:30.846890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29cd47decc2d'
down_revision: Union[str, None] = 'd1134cece895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testsprefattigroup', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testsprefattigroup', 'is_deleted')
    # ### end Alembic commands ###
