"""Initial baseline

Revision ID: 2c56da55332f
Revises: 
Create Date: 2025-03-08 13:06:31.122858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c56da55332f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('testsgroup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nr_test', sa.Integer(), nullable=False),
    sa.Column('nr_gruppo', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('in_sequenza', sa.Boolean(), nullable=False),
    sa.Column('secondi_ritardo', sa.Integer(), nullable=False),
    sa.Column('data_ora_inizio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_ora_inserimento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testsgroup_id'), 'testsgroup', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testsgroup_id'), table_name='testsgroup')
    op.drop_table('testsgroup')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
