"""Migration description

Revision ID: 5a7232e15826
Revises: d7a264365b3e
Create Date: 2025-03-27 09:40:20.964541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7232e15826'
down_revision: Union[str, None] = 'd7a264365b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domande', sa.Column('posizione', sa.Integer(), nullable=True))
    op.drop_column('domande', 'poszione')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domande', sa.Column('poszione', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('domande', 'posizione')
    # ### end Alembic commands ###
