"""Migration description

Revision ID: 6b24ff031a6e
Revises: 29cd47decc2d
Create Date: 2025-04-02 14:11:56.190682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b24ff031a6e'
down_revision: Union[str, None] = '29cd47decc2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('tests', 'malus_f5')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('malus_f5', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tests', 'is_active')
    # ### end Alembic commands ###
