"""Migration description

Revision ID: 97acdb6bef9b
Revises: 6b24ff031a6e
Create Date: 2025-04-03 08:38:27.013776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97acdb6bef9b'
down_revision: Union[str, None] = '6b24ff031a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('generated', sa.Boolean(), nullable=True))
    op.drop_column('tests', 'in_sequenza')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('in_sequenza', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tests', 'generated')
    # ### end Alembic commands ###
