"""Domande / Varianti generation

Revision ID: 97caa23a47ae
Revises: be088d3e1453
Create Date: 2025-03-10 19:39:20.327037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97caa23a47ae'
down_revision: Union[str, None] = 'be088d3e1453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domande', 'dataOraInserimento')
    op.drop_column('varianti', 'dataOraInserimento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('varianti', sa.Column('dataOraInserimento', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('domande', sa.Column('dataOraInserimento', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
