"""Migration description

Revision ID: 9df815de5bb4
Revises: 8d1563c1f010
Create Date: 2025-03-11 13:01:32.321950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df815de5bb4'
down_revision: Union[str, None] = '8d1563c1f010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistiche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_domanda', sa.String(length=50), nullable=False),
    sa.Column('nr_errori', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistiche_id'), 'statistiche', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistiche_id'), table_name='statistiche')
    op.drop_table('statistiche')
    # ### end Alembic commands ###
