"""Domande / Varianti generation

Revision ID: b8eba0cc7008
Revises: 97caa23a47ae
Create Date: 2025-03-10 19:42:37.726922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8eba0cc7008'
down_revision: Union[str, None] = '97caa23a47ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('idTest', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataOraInizio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('inSequenza', sa.Boolean(), nullable=True),
    sa.Column('nrGruppo', sa.Integer(), nullable=False),
    sa.Column('secondiRitardo', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('dataOraFine', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataOraInserimento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('nrTest', sa.Integer(), nullable=False),
    sa.Column('malusF5', sa.Boolean(), nullable=False),
    sa.Column('numeroErrori', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('idTest')
    )
    op.create_index(op.f('ix_tests_idTest'), 'tests', ['idTest'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_idTest'), table_name='tests')
    op.drop_table('tests')
    # ### end Alembic commands ###
