"""Migration description

Revision ID: b9d63760620e
Revises: 5a7232e15826
Create Date: 2025-03-27 11:36:56.513799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d63760620e'
down_revision: Union[str, None] = '5a7232e15826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('testgroup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tests', 'testsgroup', ['testgroup_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_column('tests', 'testgroup_id')
    # ### end Alembic commands ###
