"""Migration description

Revision ID: cdf25363ec41
Revises: 9df815de5bb4
Create Date: 2025-03-12 10:49:23.230986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf25363ec41'
down_revision: Union[str, None] = '9df815de5bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('tempo_impiegato', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'tempo_impiegato')
    # ### end Alembic commands ###
