"""Migration description

Revision ID: d1134cece895
Revises: 
Create Date: 2025-04-01 22:15:12.865368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1134cece895'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testsgroup', sa.Column('visibile', sa.Boolean(), nullable=True))
    op.drop_column('testsgroup', 'in_sequenza')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testsgroup', sa.Column('in_sequenza', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('testsgroup', 'visibile')
    # ### end Alembic commands ###
