"""Migration description

Revision ID: d7a264365b3e
Revises: 1af55761fccc
Create Date: 2025-03-27 09:26:54.031640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a264365b3e'
down_revision: Union[str, None] = '1af55761fccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domande', sa.Column('poszione', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domande', 'poszione')
    # ### end Alembic commands ###
